### ISSUE TITLE
Couchbase support ETA?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [jetstack/navigator#181]
/kind feature

I see you plan to have couchbase support. Are there any rough ETA on that?

Thanks

**Comment by wallrj** [comment]
Hello @DanielFerreiraJorge.

The documentation is slightly misleading. We (Jetstack) are focusing on ElasticSearch and Cassandra support right now because that's what our clients require.
We'd love to add Couchbase support this year but it depends on the amount of interest from our clients and partners.
If you'd like to discuss it further please contact @mattbates  (co-founder of Jetstack https://www.jetstack.io/about/); perhaps we can work together on it :-)

Apologies for not replying sooner.
